### ISSUE TITLE
Organizational Proposal

### ISSUE THREAD

**Issue by LeeHorobin** [OptimusPi/SKO#2]
# Organizational Proposals
## Overview

We have discussed multiple times before the possibility that I try and help withdevelopment of SKO  in any way I can. With no real familiarity with how the project is structured, I figure starting out with some documentation will be a good first step.

Hopefully, helping to write some documentation will allow me to familiarise myself with the code structure as well as make it more accessible to anybody else who would like to contribute.

Before getting started in too much detail, or committing any changes to the codebase, I would like to propose some changes in order to make collaboration and organization as easy as possible.

Please do comment with any disagreements or thoughts you might have. :)

---
### Documentation Strategy

I would like to propose implementing a documentation generator in order to force documentation to be consistent across the project and to allow easily publishing in HTML etc.

For example: [http://www.stack.nl/~dimitri/doxygen/](Doxygen)
### Styling Consistency

Agreeing on certain styling conventions to follow will help to make collaboration easier, providing consistency and ensuring an effort is made to keep the project well structured and maintained.

Perhaps [https://google.github.io/styleguide/cppguide.html](Google's C++ Style Guide)

I do not necessarily mean religiously following every single little rule, more so agreeing on things like indentation strategies etc. 

Two space indentations with no tabs :D. Editor configured to input spaces in place of tabs, that kinda thing.
### Folder Structure

I would also like to propose reorganising the project folder structure slightly. Something like this:-

| Directory | Contains |
| --- | --- |
| ./ | Makefiles, readme's, git files |
| lib/ | Project sources prividing an interface/api, OPI_Image, SKO_Shop etc |
| src/ | Project source files |
| bin/ | Any binaries, sko.exe, DLL's, that kinda thing |
| configs/ | Configuration files, ini's, maps |
| thirdparty/ | Third part sources, for example the INI parsers |

SKO_Client
├───bin
├───client_resources
│   ├───image
│   │   ├───GUI
│   │   └───TILE
│   └───sound
├───config
│   ├───data
│   └───maps
├───lib
├───src
└───thirdparty

**Comment by OptimusPi** [comment]
Have at it! You can do it! We'll do it together! 🔢

**Comment by LeeHorobin** [comment]
Closing this, lots of other re factoring to consider before considering documentation.  A lot of the proposed folder structure changes have already been implemented.
