### ISSUE TITLE
Holding 'r' will throw trophies repeatedly

### ISSUE THREAD

**Issue by OptimusPi** [OptimusPi/SKO#31]
![sko-bug-trophy-throw](https://user-images.githubusercontent.com/16853743/43872840-5e556d6a-9b49-11e8-8f51-3bbd2f3cd474.png)

**Comment by OptimusPi** [comment]
I wonder about other input keys such as spacebar, arrow keys, attack keys, etc. It's a possible cause of other bugs or lagg, perhaps including a double-jump glitch.

**Comment by LeeHorobin** [comment]
Resolved in pull request #33 :)
